[package]
name = "login"
version.workspace = true
authors.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dir = { path = "../dir" }
ureq.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
cookie_store.workspace = true
des = "0.8"
hex = "0.4"
#hex-literal = "0.4"
